# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-22 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
                ('image_name', models.CharField(max_length=30)),
                ('image_description', models.CharField(max_length=3000)),
            ],
        ),
    ]
