# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potrait', '0002_auto_20180125_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
