# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-25 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potrait', '0003_remove_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
